version: "3.9"
services:
  simulator:
    build: .
    ports:
      - "5901:5901"
      - "6080:6080"
  ur:
    image: kristoferb/ursim:latest
    privileged: true
    ports:
      - "5902:5902"
      - "6081:6080"
      - "29999:29999"
      - "30001-30004:30001-30004"
    environment:
    - VNC_PORT=5902
